"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert(
      "products",
      [
        {
          title: "Yendo de la Cama al Living",
          price: 1200,
          description: "Alguna descripcion...",
          cover: "tapa-1600989503914.jpeg",
          publish_date: "1995-10-02",
          stock: 1,
          highlight: 0,
          format_id: 1,
          artist_id: 4,
          label_id: 1,
          genre_id: 4,
        },
        {
          title: "(Whats the story?) Morning Glory",
          price: 1600,
          description: "Alguna descripcion...",
          cover: "tapa-1600911903601.jpg",
          publish_date: "1995-10-02",
          stock: 4,
          highlight: 0,
          format_id: 1,
          artist_id: 1,
          label_id: 7,
          genre_id: 2,
        },
        {
          title: "Let it be",
          price: 1800,
          description: "Alguna descripcion...",
          cover: "tapa-1600985609780.jpeg",
          publish_date: "1995-10-02",
          stock: 2,
          highlight: 1,
          format_id: 1,
          artist_id: 7,
          label_id: 8,
          genre_id: 3,
        },
        {
          title: "Sticky Fingers",
          price: 1700,
          description: "Alguna descripcion...",
          cover: "tapa-1598296642968.jpeg",
          publish_date: "1995-10-02",
          stock: 5,
          highlight: 1,
          format_id: 1,
          artist_id: 3,
          label_id: 9,
          genre_id: 3,
        },
        {
          title: "Exile on Main Street",
          price: 2000,
          description: "Alguna descripcion...",
          cover: "tapa-1598222521389.jpeg",
          publish_date: "1995-10-02",
          stock: 4,
          highlight: 1,
          format_id: 1,
          artist_id: 3,
          label_id: 9,
          genre_id: 3,
        },
        {
          title: "White Album",
          price: 1200,
          description: "Alguna descripcion...",
          cover: "tapa-1600987832469.jpeg",
          publish_date: "1995-10-02",
          stock: 1,
          highlight: 1,
          format_id: 1,
          artist_id: 7,
          label_id: 8,
          genre_id: 3,
        },
        {
          title: "AM",
          price: 1500,
          description: "Alguna descripcion...",
          cover: "tapa-1600989752817.jpeg",
          publish_date: "1995-10-02",
          stock: 7,
          highlight: 1,
          format_id: 1,
          artist_id: 12,
          label_id: 6,
          genre_id: 2,
        },
        {
          title: "Stadium Arcadium (Jupiter)",
          price: 1400,
          description: "Alguna descripcion...",
          cover: "tapa-1600986189032.jpg",
          publish_date: "1995-10-02",
          stock: 3,
          highlight: 1,
          format_id: 1,
          artist_id: 2,
          label_id: 3,
          genre_id: 5,
        },
        {
          title: "Stadium Arcadium (Mars)",
          price: 1400,
          description: "Alguna descripcion...",
          cover: "tapa-1600988438060.jpeg",
          publish_date: "1995-10-02",
          stock: 5,
          highlight: 0,
          format_id: 1,
          artist_id: 2,
          label_id: 3,
          genre_id: 5,
        },
        {
          title: "Clics Modernos",
          price: 1400,
          description: "Alguna descripcion...",
          cover: "tapa-1600989020529.jpeg",
          publish_date: "1995-10-02",
          stock: 4,
          highlight: 1,
          format_id: 1,
          artist_id: 4,
          label_id: 1,
          genre_id: 4,
        },
        {
          title: "Artaud",
          price: 1600,
          description: "Alguna descripcion...",
          cover: "tapa-1600989867601.jpeg",
          publish_date: "1995-10-02",
          stock: 3,
          highlight: 1,
          format_id: 1,
          artist_id: 5,
          label_id: 4,
          genre_id: 4,
        },
        {
          title: "Definitely Maybe",
          price: 1600,
          description: "Alguna descripcion...",
          cover: "tapa-1600811872465.jpg",
          publish_date: "1995-10-02",
          stock: 3,
          highlight: 1,
          format_id: 1,
          artist_id: 1,
          label_id: 7,
          genre_id: 2,
        },
        {
          title: "Almendra",
          price: 1200,
          description: "Alguna descripcion...",
          cover: "tapa-1600988561244.jpeg",
          publish_date: "1995-10-02",
          stock: 2,
          highlight: 1,
          format_id: 1,
          artist_id: 6,
          label_id: 6,
          genre_id: 4,
        },
        {
          title: "My Generation",
          price: 1200,
          description: "Alguna descripcion...",
          cover: "tapa-1600988715447.jpeg",
          publish_date: "1995-10-02",
          stock: 1,
          highlight: 0,
          format_id: 1,
          artist_id: 8,
          label_id: 10,
          genre_id: 3,
        },
        {
          title: "Viva la Vida or Death and All His Friends",
          price: 1600,
          description: "Alguna descripcion...",
          cover: "tapa-1600988785317.jpeg",
          publish_date: "1995-10-02",
          stock: 2,
          highlight: 0,
          format_id: 1,
          artist_id: 9,
          label_id: 11,
          genre_id: 2,
        },
        {
          title: "Parachutes",
          price: 1800,
          description: "Alguna descripcion...",
          cover: "tapa-1600989133175.jpeg",
          publish_date: "1995-10-02",
          stock: 2,
          highlight: 1,
          format_id: 1,
          artist_id: 9,
          label_id: 11,
          genre_id: 2,
        },
        {
          title: "Axis: Bold as Love",
          price: 1600,
          description: "Alguna descripcion...",
          cover: "tapa-1600985097832.jpeg",
          publish_date: "1995-10-02",
          stock: 3,
          highlight: 0,
          format_id: 1,
          artist_id: 10,
          label_id: 12,
          genre_id: 17,
        },
        {
          title: "Blur",
          price: 1200,
          description: "Alguna descripcion...",
          cover: "tapa-1600985172540.jpeg",
          publish_date: "1995-10-02",
          stock: 5,
          highlight: 0,
          format_id: 1,
          artist_id: 11,
          label_id: 13,
          genre_id: 2,
        },
        {
          title: "Californication",
          price: 1700,
          description: "Alguna descripcion...",
          cover: "tapa-1600912101879.jpeg",
          publish_date: "1995-10-02",
          stock: 6,
          highlight: 0,
          format_id: 1,
          artist_id: 2,
          label_id: 3,
          genre_id: 5,
        },
        {
          title: "Dark Side of The Moon",
          price: 1200,
          description: "Alguna descripcion...",
          cover: "tapa-1600985292612.jpeg",
          publish_date: "1995-10-02",
          stock: 8,
          highlight: 1,
          format_id: 1,
          artist_id: 13,
          label_id: 11,
          genre_id: 17,
        },
        {
          title:
            "The Rise and Fall of Ziggy Stardust and the Spiders from Mars",
          price: 1500,
          description: "Alguna descripcion...",
          cover: "tapa-1600985404124.jpeg",
          publish_date: "1995-10-02",
          stock: 4,
          highlight: 0,
          format_id: 1,
          artist_id: 14,
          label_id: 9,
          genre_id: 19,
        },
        {
          title: "A Night at The Opera",
          price: 1900,
          description: "Alguna descripcion...",
          cover: "tapa-1600985452838.jpeg",
          publish_date: "1995-10-02",
          stock: 7,
          highlight: 1,
          format_id: 1,
          artist_id: 15,
          label_id: 5,
          genre_id: 20,
        },
        {
          title: "Queen II",
          price: 1600,
          description: "Alguna descripcion...",
          cover: "tapa-1600985500831.jpeg",
          publish_date: "1995-10-02",
          stock: 4,
          highlight: 1,
          format_id: 1,
          artist_id: 15,
          label_id: 5,
          genre_id: 20,
        },
        {
          title: "Tattoo You",
          price: 1700,
          description: "Alguna descripcion...",
          cover: "tapa-1600984732322.jpeg",
          publish_date: "1995-10-02",
          stock: 3,
          highlight: 0,
          format_id: 1,
          artist_id: 3,
          label_id: 1,
          genre_id: 3,
        },
        {
          title: "Sgt. Pepper's Lonely Hearts Club Band",
          price: 1200,
          description: "Alguna descripcion...",
          cover: "tapa-1600984834013.jpeg",
          publish_date: "1995-10-02",
          stock: 5,
          highlight: 1,
          format_id: 1,
          artist_id: 7,
          label_id: 8,
          genre_id: 3,
        },
        {
          title: "Houses of The Holy",
          price: 2200,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225076.jpeg",
          publish_date: "1995-10-02",
          stock: 5,
          highlight: 1,
          format_id: 1,
          artist_id: 16,
          label_id: 14,
          genre_id: 18,
        },
        {
          title: "Free Wheelin' Bob Dylan",
          price: 3000,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225077.jpg",
          publish_date: "1963-05-27",
          stock: 7,
          highlight: 0,
          format_id: 1,
          artist_id: 17,
          label_id: 2,
          genre_id: 21,
        },
        {
          title: "MTV Unplugged",
          price: 2700,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225078.jpg",
          publish_date: "1992-08-25",
          stock: 9,
          highlight: 1,
          format_id: 1,
          artist_id: 18,
          label_id: 15,
          genre_id: 3,
        },
        {
          title: "Rumours",
          price: 2000,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225079.jpg",
          publish_date: "1977-02-04",
          stock: 11,
          highlight: 0,
          format_id: 1,
          artist_id: 19,
          label_id: 3,
          genre_id: 3,
        },
        {
          title: "Cosmo's Factory",
          price: 2300,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225080.jpeg",
          publish_date: "1970-07-25",
          stock: 8,
          highlight: 1,
          format_id: 1,
          artist_id: 20,
          label_id: 16,
          genre_id: 3,
        },
        {
          title: "Appetite for Destruction",
          price: 2800,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225081.webp",
          publish_date: "1987-07-21",
          stock: 10,
          highlight: 1,
          format_id: 1,
          artist_id: 21,
          label_id: 17,
          genre_id: 18,
        },
        {
          title: "Back in Black",
          price: 3000,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225082.jpg",
          publish_date: "1980-07-05",
          stock: 12,
          highlight: 1,
          format_id: 1,
          artist_id: 22,
          label_id: 14,
          genre_id: 18,
        },
        {
          title: "Slippery When Wet",
          price: 2900,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225083.jpg",
          publish_date: "1986-08-18",
          stock: 9,
          highlight: 0,
          format_id: 1,
          artist_id: 23,
          label_id: 18,
          genre_id: 19,
        },
        {
          title: "Canción Animal",
          price: 1900,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225084.jpg",
          publish_date: "1990-08-07",
          stock: 12,
          highlight: 1,
          format_id: 1,
          artist_id: 24,
          label_id: 19,
          genre_id: 4,
        },
        {
          title: "Fuerza Natrual",
          price: 2200,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225085.jpg",
          publish_date: "2009-09-01",
          stock: 9,
          highlight: 1,
          format_id: 1,
          artist_id: 25,
          label_id: 6,
          genre_id: 4,
        },
        {
          title: "Pelusón of Milk",
          price: 2000,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225086.jpg",
          publish_date: "1991-09-01",
          stock: 8,
          highlight: 0,
          format_id: 1,
          artist_id: 26,
          label_id: 5,
          genre_id: 4,
        },
        {
          title: "Fabulosos Calavera",
          price: 1900,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225087.jpg",
          publish_date: "1997-07-28",
          stock: 8,
          highlight: 1,
          format_id: 1,
          artist_id: 27,
          label_id: 20,
          genre_id: 4,
        },
        {
          title: "Get a Grip",
          price: 2300,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225088.jpg",
          publish_date: "1993-04-20",
          stock: 9,
          highlight: 0,
          format_id: 1,
          artist_id: 28,
          label_id: 17,
          genre_id: 1,
        },
        {
          title: "Continuum",
          price: 2400,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225089.jpg",
          publish_date: "2006-09-12",
          stock: 11,
          highlight: 1,
          format_id: 1,
          artist_id: 29,
          label_id: 2,
          genre_id: 10,
        },
        {
          title: "MTV Unplugged",
          price: 2900,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225090.jpg",
          publish_date: "1994-10-01",
          stock: 4,
          highlight: 1,
          format_id: 1,
          artist_id: 30,
          label_id: 17,
          genre_id: 11,
        },
        {
          title: "The Colour and The Shade",
          price: 2300,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225091.png",
          publish_date: "1997-05-20",
          stock: 6,
          highlight: 0,
          format_id: 1,
          artist_id: 31,
          label_id: 11,
          genre_id: 22,
        },
        {
          title: "Franz Ferdinand",
          price: 2200,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225092.jpg",
          publish_date: "2004-02-09",
          stock: 7,
          highlight: 0,
          format_id: 1,
          artist_id: 32,
          label_id: 21,
          genre_id: 22,
        },
        {
          title: "Goodbye Yellow Brick Road",
          price: 2400,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225093.jpg",
          publish_date: "1973-10-05",
          stock: 6,
          highlight: 1,
          format_id: 1,
          artist_id: 33,
          label_id: 22,
          genre_id: 19,
        },
        {
          title: "Mama Said",
          price: 2200,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225094.jpg",
          publish_date: "1991-04-02",
          stock: 9,
          highlight: 0,
          format_id: 1,
          artist_id: 34,
          label_id: 9,
          genre_id: 1,
        },
        {
          title: "12 Segundos de Oscuridad",
          price: 2400,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225095.jpg",
          publish_date: "2006-09-18",
          stock: 9,
          highlight: 1,
          format_id: 1,
          artist_id: 35,
          label_id: 3,
          genre_id: 12,
        },
        {
          title: "Abbey Road",
          price: 3000,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225096.jpg",
          publish_date: "1969-09-26",
          stock: 7,
          highlight: 1,
          format_id: 1,
          artist_id: 7,
          label_id: 8,
          genre_id: 3,
        },
        {
          title: "Some Girsl",
          price: 2400,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225097.jpg",
          publish_date: "1978-06-09",
          stock: 9,
          highlight: 1,
          format_id: 1,
          artist_id: 3,
          label_id: 9,
          genre_id: 3,
        },
        {
          title: "Toys in The Attic",
          price: 2600,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225098.jpeg",
          publish_date: "1975-04-08",
          stock: 6,
          highlight: 0,
          format_id: 1,
          artist_id: 28,
          label_id: 2,
          genre_id: 18,
        },
        {
          title: "In Utero",
          price: 2800,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225099.jpg",
          publish_date: "1993-09-21",
          stock: 8,
          highlight: 1,
          format_id: 1,
          artist_id: 30,
          label_id: 23,
          genre_id: 11,
        },
        {
          title: "Slowhand",
          price: 2500,
          description: "Alguna descripcion...",
          cover: "tapa-1601183225100.jpg",
          publish_date: "1977-11-25",
          stock: 6,
          highlight: 0,
          format_id: 1,
          artist_id: 18,
          label_id: 24,
          genre_id: 10,
        }
      ],
      {}
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("products", null, {});
  },
};
